# Generated by Django 5.2.8 on 2025-12-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_modules', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
