# Generated by Django 5.2.8 on 2026-01-13 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_positions_position'),
        ('employee_modules', '0004_employee_created_employee_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.position'),
        ),
    ]
