# Generated by Django 5.2.8 on 2026-03-09 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_modules', '0005_alter_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePersonalDataSheet',
            fields=[
                ('pds_id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('name_extension', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=150)),
                ('sex', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=10)),
                ('civil_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('annulled', 'Annulled'), ('other', 'Other')], max_length=20)),
                ('civil_status_other', models.CharField(blank=True, max_length=100)),
                ('citizenship', models.CharField(blank=True, max_length=100)),
                ('citizenship_basis', models.CharField(blank=True, choices=[('by_birth', 'By Birth'), ('by_naturalization', 'By Naturalization')], max_length=30)),
                ('dual_citizenship_country', models.CharField(blank=True, max_length=100)),
                ('height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=20)),
                ('gsis_id_no', models.CharField(blank=True, max_length=50)),
                ('pagibig_id_no', models.CharField(blank=True, max_length=50)),
                ('philhealth_no', models.CharField(blank=True, max_length=50)),
                ('sss_no', models.CharField(blank=True, max_length=50)),
                ('tin_no', models.CharField(blank=True, max_length=50)),
                ('agency_employee_no', models.CharField(blank=True, max_length=50)),
                ('residential_address', models.JSONField(blank=True, default=dict)),
                ('permanent_address', models.JSONField(blank=True, default=dict)),
                ('telephone_no', models.CharField(blank=True, max_length=50)),
                ('mobile_no', models.CharField(blank=True, max_length=50)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('spouse_information', models.JSONField(blank=True, default=dict)),
                ('father_information', models.JSONField(blank=True, default=dict)),
                ('mother_information', models.JSONField(blank=True, default=dict)),
                ('children', models.JSONField(blank=True, default=list)),
                ('educational_background', models.JSONField(blank=True, default=dict)),
                ('civil_service_eligibilities', models.JSONField(blank=True, default=list)),
                ('work_experiences', models.JSONField(blank=True, default=list)),
                ('voluntary_works', models.JSONField(blank=True, default=list)),
                ('learning_and_development', models.JSONField(blank=True, default=list)),
                ('special_skills', models.JSONField(blank=True, default=list)),
                ('recognitions', models.JSONField(blank=True, default=list)),
                ('memberships', models.JSONField(blank=True, default=list)),
                ('questionnaire', models.JSONField(blank=True, default=dict)),
                ('references', models.JSONField(blank=True, default=list)),
                ('government_id_type', models.CharField(blank=True, max_length=100)),
                ('government_id_number', models.CharField(blank=True, max_length=100)),
                ('government_id_date_of_issue', models.DateField(blank=True, null=True)),
                ('government_id_place_of_issue', models.CharField(blank=True, max_length=150)),
                ('date_accomplished', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_data_sheet', to='employee_modules.employee')),
            ],
            options={
                'ordering': ['employee__last_name', 'employee__first_name'],
            },
        ),
    ]
