# Generated by Django 5.2.8 on 2026-01-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_positions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Positions',
            new_name='Position',
        ),
    ]
