# Generated by Django 5.2.8 on 2026-01-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_positions_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRule',
            fields=[
                ('time_rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_rule_name', models.CharField(max_length=100, unique=True)),
                ('earliest_in', models.TimeField()),
                ('latest_in', models.TimeField()),
                ('earliest_out', models.TimeField()),
                ('latest_out', models.TimeField()),
                ('lunch_start', models.TimeField()),
                ('lunch_end', models.TimeField()),
                ('lunch_grace_period', models.IntegerField(help_text='Grace period in minutes')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
