# Generated by Django 5.2.8 on 2026-03-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_timerule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryGrade',
            fields=[
                ('salary_grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('csc_grade', models.PositiveSmallIntegerField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['csc_grade'],
            },
        ),
    ]
