# Generated by Django 5.2.8 on 2026-03-09 08:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_salarygrade_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSCPlantilla',
            fields=[
                ('plantilla_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_number', models.CharField(max_length=50, unique=True)),
                ('salary_step', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.division')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.position')),
                ('salary_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.salarygrade')),
            ],
            options={
                'ordering': ['item_number'],
            },
        ),
    ]
