# Generated by Django 5.2.8 on 2026-03-10 01:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_position_standard_salary_grade_and_plantilla_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('leave_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_code', models.CharField(max_length=30, unique=True)),
                ('leave_name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('credit_based', 'Credit-based Leave'), ('statutory', 'Statutory Leave'), ('special', 'Special Leave Privilege'), ('conversion', 'Credit Conversion / Separation'), ('wellness', 'Wellness Leave')], default='statutory', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('legal_basis', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_seed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['sort_order', 'leave_name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveTypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_status', models.CharField(choices=[('with_pay', 'With Pay'), ('without_pay', 'Without Pay'), ('chargeable_to_credits', 'Chargeable to Leave Credits'), ('conditional', 'Conditional / Depends on Rule')], default='with_pay', max_length=30)),
                ('credit_deduction_mode', models.CharField(choices=[('none', 'Not Deducted from Leave Credits'), ('vacation', 'Vacation Leave Credits'), ('sick', 'Sick Leave Credits'), ('vacation_or_sick', 'Vacation / Sick Leave Credits'), ('separate', 'Separate Statutory Entitlement')], default='none', max_length=30)),
                ('entitlement_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('entitlement_unit', models.CharField(choices=[('working_days', 'Working Days'), ('calendar_days', 'Calendar Days'), ('months', 'Months'), ('credit_balance', 'Available Leave Credit Balance')], default='working_days', max_length=30)),
                ('entitlement_period', models.CharField(choices=[('per_application', 'Per Application'), ('per_year', 'Per Year'), ('per_occurrence', 'Per Occurrence'), ('on_separation', 'Upon Separation'), ('not_fixed', 'Not Fixed')], default='per_application', max_length=30)),
                ('min_service_months_required', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('advance_notice_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_consecutive_days', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('requires_earned_leave_credits', models.BooleanField(default=False)),
                ('allows_intermittent', models.BooleanField(default=False)),
                ('requires_supporting_document', models.BooleanField(default=False)),
                ('supporting_document_notes', models.TextField(blank=True)),
                ('eligibility_notes', models.TextField(blank=True)),
                ('filing_notes', models.TextField(blank=True)),
                ('rule_notes', models.TextField(blank=True)),
                ('leave_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='core.leavetype')),
            ],
        ),
    ]
