from decimal import Decimal

from django.db import migrations


LEAVE_TYPES = [
    {
        "leave_code": "VL",
        "leave_name": "Vacation Leave",
        "category": "credit_based",
        "description": "Leave of absence for personal reasons, rest, and recreation chargeable against earned vacation leave credits.",
        "legal_basis": "CSC Omnibus Rules on Leave; CS Form No. 6, Revised 2020",
        "sort_order": 10,
        "rule": {
            "pay_status": "chargeable_to_credits",
            "credit_deduction_mode": "vacation",
            "entitlement_value": None,
            "entitlement_unit": "credit_balance",
            "entitlement_period": "not_fixed",
            "min_service_months_required": None,
            "advance_notice_days": 5,
            "max_consecutive_days": None,
            "requires_earned_leave_credits": True,
            "allows_intermittent": True,
            "requires_supporting_document": False,
            "supporting_document_notes": "Personal notice is generally sufficient unless agency rules require additional documentation.",
            "eligibility_notes": "Available to officials and employees with earned vacation leave credits.",
            "filing_notes": "File five days in advance whenever possible.",
            "rule_notes": "If vacation leave credits are insufficient, the leave may be without pay subject to agency approval.",
        },
    },
    {
        "leave_code": "FVL",
        "leave_name": "Mandatory / Forced Leave",
        "category": "credit_based",
        "description": "Five-day annual forced leave imposed on employees with sufficient vacation leave credits.",
        "legal_basis": "Executive Order No. 1077; CSC Omnibus Rules on Leave",
        "sort_order": 20,
        "rule": {
            "pay_status": "chargeable_to_credits",
            "credit_deduction_mode": "vacation",
            "entitlement_value": Decimal("5.00"),
            "entitlement_unit": "working_days",
            "entitlement_period": "per_year",
            "min_service_months_required": None,
            "advance_notice_days": None,
            "max_consecutive_days": Decimal("5.00"),
            "requires_earned_leave_credits": True,
            "allows_intermittent": True,
            "requires_supporting_document": False,
            "supporting_document_notes": "",
            "eligibility_notes": "Applies to employees with at least ten earned vacation leave credits.",
            "filing_notes": "Scheduling is usually set by the agency during the calendar year.",
            "rule_notes": "Unused mandatory leave is generally forfeited and cannot be carried over.",
        },
    },
    {
        "leave_code": "SL",
        "leave_name": "Sick Leave",
        "category": "credit_based",
        "description": "Leave of absence on account of illness or disability chargeable against earned sick leave credits.",
        "legal_basis": "CSC Omnibus Rules on Leave; CS Form No. 6, Revised 2020",
        "sort_order": 30,
        "rule": {
            "pay_status": "chargeable_to_credits",
            "credit_deduction_mode": "sick",
            "entitlement_value": None,
            "entitlement_unit": "credit_balance",
            "entitlement_period": "not_fixed",
            "min_service_months_required": None,
            "advance_notice_days": None,
            "max_consecutive_days": None,
            "requires_earned_leave_credits": True,
            "allows_intermittent": True,
            "requires_supporting_document": True,
            "supporting_document_notes": "Medical certificate is required for absences of more than five days or when requested by the agency.",
            "eligibility_notes": "Available to officials and employees with earned sick leave credits.",
            "filing_notes": "If filed after the leave, submit immediately upon return to duty.",
            "rule_notes": "Agency may require proof of illness for frequent or extended sick leave applications.",
        },
    },
    {
        "leave_code": "ML",
        "leave_name": "Maternity Leave",
        "category": "statutory",
        "description": "Paid maternity leave for live childbirth, miscarriage, or emergency termination of pregnancy under the expanded maternity leave rules.",
        "legal_basis": "Republic Act No. 11210; CSC Resolution No. 2100020; CSC MC No. 05, s. 2021",
        "sort_order": 40,
        "rule": {
            "pay_status": "with_pay",
            "credit_deduction_mode": "separate",
            "entitlement_value": Decimal("105.00"),
            "entitlement_unit": "calendar_days",
            "entitlement_period": "per_occurrence",
            "min_service_months_required": None,
            "advance_notice_days": None,
            "max_consecutive_days": Decimal("105.00"),
            "requires_earned_leave_credits": False,
            "allows_intermittent": False,
            "requires_supporting_document": True,
            "supporting_document_notes": "Medical proof of pregnancy or delivery documents are required. Emergency termination cases use medical certification.",
            "eligibility_notes": "Granted regardless of civil status or employment status subject to the expanded maternity leave law.",
            "filing_notes": "Advance notice should be given when practicable and supported by the expected date of delivery.",
            "rule_notes": "Solo parents are entitled to an additional 15 days. Miscarriage or emergency termination is covered by the applicable CSC maternity rules.",
        },
    },
    {
        "leave_code": "PAT",
        "leave_name": "Paternity Leave",
        "category": "statutory",
        "description": "Paid paternity leave for the legitimate spouse's first four deliveries or miscarriages.",
        "legal_basis": "Republic Act No. 8187; CSC Resolution No. 2100020",
        "sort_order": 50,
        "rule": {
            "pay_status": "with_pay",
            "credit_deduction_mode": "separate",
            "entitlement_value": Decimal("7.00"),
            "entitlement_unit": "calendar_days",
            "entitlement_period": "per_occurrence",
            "min_service_months_required": None,
            "advance_notice_days": None,
            "max_consecutive_days": Decimal("7.00"),
            "requires_earned_leave_credits": False,
            "allows_intermittent": False,
            "requires_supporting_document": True,
            "supporting_document_notes": "Proof of spouse's pregnancy or delivery and proof of relationship may be required.",
            "eligibility_notes": "Available only for the first four deliveries or miscarriages of the legitimate spouse with whom the employee is cohabiting.",
            "filing_notes": "File before or immediately after the availment with the required documentary proof.",
            "rule_notes": "Full pay is granted for seven days per qualified occasion.",
        },
    },
    {
        "leave_code": "SPL",
        "leave_name": "Special Privilege Leave",
        "category": "special",
        "description": "Special leave privilege to mark personal milestones and attend to family or civic obligations.",
        "legal_basis": "CSC MC No. 06, s. 2006; CSC MC No. 02, s. 2019; CS Form No. 6, Revised 2020",
        "sort_order": 60,
        "rule": {
            "pay_status": "with_pay",
            "credit_deduction_mode": "none",
            "entitlement_value": Decimal("3.00"),
            "entitlement_unit": "working_days",
            "entitlement_period": "per_year",
            "min_service_months_required": None,
            "advance_notice_days": 7,
            "max_consecutive_days": Decimal("3.00"),
            "requires_earned_leave_credits": False,
            "allows_intermittent": True,
            "requires_supporting_document": False,
            "supporting_document_notes": "Agency may ask for proof depending on the specific occasion claimed.",
            "eligibility_notes": "Available to employees subject to agency operations and service exigencies.",
            "filing_notes": "File at least one week in advance, except in emergency cases.",
            "rule_notes": "Not deducted from vacation or sick leave credits.",
        },
    },
    {
        "leave_code": "SOLP",
        "leave_name": "Solo Parent Leave",
        "category": "statutory",
        "description": "Leave privilege for qualified solo parents to attend to parental duties and responsibilities.",
        "legal_basis": "Republic Act No. 8972; Republic Act No. 11861; CSC leave application guidance",
        "sort_order": 70,
        "rule": {
            "pay_status": "with_pay",
            "credit_deduction_mode": "separate",
            "entitlement_value": Decimal("7.00"),
            "entitlement_unit": "working_days",
            "entitlement_period": "per_year",
            "min_service_months_required": None,
            "advance_notice_days": 5,
            "max_consecutive_days": Decimal("7.00"),
            "requires_earned_leave_credits": False,
            "allows_intermittent": True,
            "requires_supporting_document": True,
            "supporting_document_notes": "Solo Parent ID and supporting proof under the Solo Parents' Welfare Act are required.",
            "eligibility_notes": "Available to qualified solo parents recognized under law.",
            "filing_notes": "Submit at least five working days in advance whenever practicable.",
            "rule_notes": "This entitlement is separate from vacation and sick leave credits.",
        },
    },
    {
        "leave_code": "STL",
        "leave_name": "Study Leave",
        "category": "special",
        "description": "Study leave granted to prepare for bar or board examinations or complete a master's degree.",
        "legal_basis": "CSC-DBM Joint Circular No. 1, s. 2004",
        "sort_order": 80,
        "rule": {
            "pay_status": "with_pay",
            "credit_deduction_mode": "none",
            "entitlement_value": Decimal("6.00"),
            "entitlement_unit": "months",
            "entitlement_period": "per_application",
            "min_service_months_required": Decimal("24.00"),
            "advance_notice_days": None,
            "max_consecutive_days": None,
            "requires_earned_leave_credits": False,
            "allows_intermittent": False,
            "requires_supporting_document": True,
            "supporting_document_notes": "Approved study plan, proof of examination or academic program, and service contract are typically required.",
            "eligibility_notes": "Generally limited to permanent employees with at least two years of service and very satisfactory performance.",
            "filing_notes": "File before the intended study period with all supporting approvals.",
            "rule_notes": "Granted for bar/board review or completion of a master's degree subject to agency staffing requirements.",
        },
    },
    {
        "leave_code": "VAWC",
        "leave_name": "10-Day VAWC Leave",
        "category": "statutory",
        "description": "Leave for women employees who are victims under the Anti-Violence Against Women and Their Children Act.",
        "legal_basis": "Republic Act No. 9262; CSC leave application guidance",
        "sort_order": 90,
        "rule": {
            "pay_status": "with_pay",
            "credit_deduction_mode": "separate",
            "entitlement_value": Decimal("10.00"),
            "entitlement_unit": "working_days",
            "entitlement_period": "per_occurrence",
            "min_service_months_required": None,
            "advance_notice_days": None,
            "max_consecutive_days": Decimal("10.00"),
            "requires_earned_leave_credits": False,
            "allows_intermittent": True,
            "requires_supporting_document": True,
            "supporting_document_notes": "Protection order, police report, prosecutor certification, or barangay certification may be required.",
            "eligibility_notes": "Available to female employees who are victims under the VAWC law.",
            "filing_notes": "File as soon as practicable, considering the circumstances of the case.",
            "rule_notes": "Court may extend the leave when warranted under the law.",
        },
    },
    {
        "leave_code": "REHAB",
        "leave_name": "Rehabilitation Privilege",
        "category": "special",
        "description": "Leave privilege for recovery from wounds or injuries sustained while performing official duties.",
        "legal_basis": "CSC MC No. 06, s. 2005; Rehabilitation Privilege program guidance",
        "sort_order": 100,
        "rule": {
            "pay_status": "with_pay",
            "credit_deduction_mode": "none",
            "entitlement_value": Decimal("6.00"),
            "entitlement_unit": "months",
            "entitlement_period": "per_occurrence",
            "min_service_months_required": None,
            "advance_notice_days": None,
            "max_consecutive_days": None,
            "requires_earned_leave_credits": False,
            "allows_intermittent": True,
            "requires_supporting_document": True,
            "supporting_document_notes": "Medical report, agency accident report, and proof that the injury was sustained in the performance of duties are required.",
            "eligibility_notes": "Applies only to work-connected injuries or wounds requiring rehabilitation.",
            "filing_notes": "Application should be initiated promptly and supported by the agency head's recommendation.",
            "rule_notes": "May be availed of intermittently or on a half-time basis depending on medical advice.",
        },
    },
    {
        "leave_code": "SLBW",
        "leave_name": "Special Leave Benefits for Women",
        "category": "statutory",
        "description": "Leave benefit for women undergoing surgery caused by gynecological disorders.",
        "legal_basis": "Republic Act No. 9710; CSC MC No. 25, s. 2010",
        "sort_order": 110,
        "rule": {
            "pay_status": "with_pay",
            "credit_deduction_mode": "separate",
            "entitlement_value": Decimal("2.00"),
            "entitlement_unit": "months",
            "entitlement_period": "per_occurrence",
            "min_service_months_required": Decimal("6.00"),
            "advance_notice_days": 5,
            "max_consecutive_days": None,
            "requires_earned_leave_credits": False,
            "allows_intermittent": False,
            "requires_supporting_document": True,
            "supporting_document_notes": "Medical certificate and proof of surgery due to a gynecological disorder are required.",
            "eligibility_notes": "Requires at least six months of aggregate service within the last 12 months.",
            "filing_notes": "File in advance whenever possible, with supporting medical documentation.",
            "rule_notes": "Granted for up to two months depending on the medical recommendation.",
        },
    },
    {
        "leave_code": "SEL",
        "leave_name": "Special Emergency (Calamity) Leave",
        "category": "special",
        "description": "Leave for employees directly affected by natural calamities or disasters recognized by competent authorities.",
        "legal_basis": "CSC Resolution No. 1200289; CSC calamity leave guidance",
        "sort_order": 120,
        "rule": {
            "pay_status": "with_pay",
            "credit_deduction_mode": "none",
            "entitlement_value": Decimal("5.00"),
            "entitlement_unit": "working_days",
            "entitlement_period": "per_occurrence",
            "min_service_months_required": None,
            "advance_notice_days": None,
            "max_consecutive_days": Decimal("5.00"),
            "requires_earned_leave_credits": False,
            "allows_intermittent": True,
            "requires_supporting_document": True,
            "supporting_document_notes": "Proof that the employee's residence or place of work is affected by the calamity may be required.",
            "eligibility_notes": "Available when a state of calamity is declared or when the agency recognizes a qualifying emergency situation.",
            "filing_notes": "Application should be filed within 30 days from the onset of the calamity.",
            "rule_notes": "This leave is separate from vacation and sick leave credits.",
        },
    },
    {
        "leave_code": "MON",
        "leave_name": "Monetization of Leave Credits",
        "category": "conversion",
        "description": "Conversion of earned leave credits into cash subject to CSC and DBM rules.",
        "legal_basis": "CSC and DBM monetization rules; CS Form No. 6, Revised 2020",
        "sort_order": 130,
        "rule": {
            "pay_status": "chargeable_to_credits",
            "credit_deduction_mode": "vacation_or_sick",
            "entitlement_value": None,
            "entitlement_unit": "credit_balance",
            "entitlement_period": "per_application",
            "min_service_months_required": None,
            "advance_notice_days": None,
            "max_consecutive_days": None,
            "requires_earned_leave_credits": True,
            "allows_intermittent": False,
            "requires_supporting_document": True,
            "supporting_document_notes": "Written request and supporting justification are usually required, especially for monetization beyond the minimum threshold.",
            "eligibility_notes": "Subject to the monetization thresholds and limitations under existing CSC/DBM rules.",
            "filing_notes": "File the monetization request through the agency's HR and finance process.",
            "rule_notes": "This is a leave-credit conversion privilege rather than a day-based absence from work.",
        },
    },
    {
        "leave_code": "TL",
        "leave_name": "Terminal Leave",
        "category": "conversion",
        "description": "Money value of accumulated vacation and sick leave credits upon separation from service.",
        "legal_basis": "CSC Omnibus Rules on Leave; terminal leave computation rules",
        "sort_order": 140,
        "rule": {
            "pay_status": "chargeable_to_credits",
            "credit_deduction_mode": "vacation_or_sick",
            "entitlement_value": None,
            "entitlement_unit": "credit_balance",
            "entitlement_period": "on_separation",
            "min_service_months_required": None,
            "advance_notice_days": None,
            "max_consecutive_days": None,
            "requires_earned_leave_credits": True,
            "allows_intermittent": False,
            "requires_supporting_document": True,
            "supporting_document_notes": "Requires proof of separation such as resignation, retirement, or other separation papers.",
            "eligibility_notes": "Available only upon separation from service and based on accumulated leave credits.",
            "filing_notes": "Process after final separation clearance and payroll/finance coordination.",
            "rule_notes": "Terminal leave is a benefit conversion, not an active leave of absence from duty.",
        },
    },
    {
        "leave_code": "ADL",
        "leave_name": "Adoption Leave",
        "category": "statutory",
        "description": "Paid adoption leave for adoptive parents under the domestic adoption rules.",
        "legal_basis": "Republic Act No. 8552; CSC Resolution No. 2100020; CSC MC No. 05, s. 2021",
        "sort_order": 150,
        "rule": {
            "pay_status": "with_pay",
            "credit_deduction_mode": "separate",
            "entitlement_value": Decimal("60.00"),
            "entitlement_unit": "calendar_days",
            "entitlement_period": "per_occurrence",
            "min_service_months_required": None,
            "advance_notice_days": None,
            "max_consecutive_days": Decimal("60.00"),
            "requires_earned_leave_credits": False,
            "allows_intermittent": False,
            "requires_supporting_document": True,
            "supporting_document_notes": "Authenticated copy of the Pre-Adoptive Placement Authority or equivalent adoption documents is required.",
            "eligibility_notes": "Available to qualified adoptive parents under the adoption law and CSC rules.",
            "filing_notes": "File with the adoption documents before or immediately after placement as applicable.",
            "rule_notes": "Separate paid entitlement and not deducted from vacation or sick leave credits.",
        },
    },
    {
        "leave_code": "WELL",
        "leave_name": "Wellness Leave",
        "category": "wellness",
        "description": "Leave privilege for personal health and wellness activities of qualified government workers.",
        "legal_basis": "CSC Resolution No. 2501292; CSC Memorandum Circular No. 6, s. 2026",
        "sort_order": 160,
        "rule": {
            "pay_status": "with_pay",
            "credit_deduction_mode": "none",
            "entitlement_value": Decimal("5.00"),
            "entitlement_unit": "working_days",
            "entitlement_period": "per_year",
            "min_service_months_required": None,
            "advance_notice_days": 5,
            "max_consecutive_days": Decimal("3.00"),
            "requires_earned_leave_credits": False,
            "allows_intermittent": True,
            "requires_supporting_document": False,
            "supporting_document_notes": "",
            "eligibility_notes": "Available under the terms of the CSC wellness leave rules beginning 2026.",
            "filing_notes": "Applications should be scheduled in advance in line with agency service requirements.",
            "rule_notes": "Wellness leave is non-cumulative, non-commutative, and may be taken for up to three consecutive days at a time.",
        },
    },
]


def seed_leave_types(apps, schema_editor):
    LeaveType = apps.get_model("core", "LeaveType")
    LeaveTypeRule = apps.get_model("core", "LeaveTypeRule")

    for record in LEAVE_TYPES:
        leave_type_data = record.copy()
        rule_data = leave_type_data.pop("rule")
        leave_type_data["is_active"] = True
        leave_type_data["is_system_seed"] = True
        leave_type_data["created_by"] = "system_seed"
        leave_type_data["modified_by"] = "system_seed"

        leave_type, _ = LeaveType.objects.update_or_create(
            leave_code=leave_type_data["leave_code"],
            defaults=leave_type_data,
        )

        LeaveTypeRule.objects.update_or_create(
            leave_type=leave_type,
            defaults=rule_data,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_leavetype_leavetyperule"),
    ]

    operations = [
        migrations.RunPython(seed_leave_types, migrations.RunPython.noop),
    ]
