# Generated by Django 5.2.8 on 2026-03-10 02:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_seed_leave_types'),
        ('employee_modules', '0007_seed_personal_data_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetyperule',
            name='balance_tracking_mode',
            field=models.CharField(choices=[('none', 'Do Not Track Against a Balance Bucket'), ('vacation', 'Track Against Vacation Leave Credits'), ('sick', 'Track Against Sick Leave Credits'), ('vacation_or_sick', 'Track Against Vacation / Sick Leave Credits'), ('leave_type', "Track Against the Leave Type's Own Balance Bucket")], default='none', max_length=30),
        ),
        migrations.CreateModel(
            name='EmployeeLeaveCredit',
            fields=[
                ('leave_credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('bucket_code', models.CharField(max_length=30)),
                ('bucket_name', models.CharField(max_length=150)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_credits', to='employee_modules.employee')),
                ('linked_leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_leave_credits', to='core.leavetype')),
            ],
            options={
                'ordering': ['employee__last_name', 'employee__first_name', 'bucket_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveCreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('opening', 'Opening Balance'), ('accrual', 'Accrual'), ('adjustment', 'Manual Adjustment'), ('deduction', 'Leave Deduction'), ('reversal', 'Reversal')], max_length=20)),
                ('units_delta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('effective_date', models.DateField()),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('leave_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.employeeleavecredit')),
            ],
            options={
                'ordering': ['-effective_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('leave_application_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('requested_units', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('supporting_document_reference', models.CharField(blank=True, max_length=255)),
                ('supporting_document_notes', models.TextField(blank=True)),
                ('balance_bucket_code', models.CharField(blank=True, max_length=30)),
                ('deducted_units', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rule_snapshot', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='employee_modules.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='core.leavetype')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddConstraint(
            model_name='employeeleavecredit',
            constraint=models.UniqueConstraint(fields=('employee', 'bucket_code'), name='unique_employee_leave_credit_bucket'),
        ),
    ]
