# Generated by Django 5.2.8 on 2026-03-12 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_seed_leave_without_pay'),
        ('employee_modules', '0008_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplicationApproval',
            fields=[
                ('leave_application_approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('approver_role', models.CharField(choices=[('immediate_supervisor', 'Immediate Supervisor'), ('division_chief', 'Division Chief'), ('hr_approver', 'HR Approver')], max_length=30)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('decision_notes', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('approver_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approval_queue', to='employee_modules.employee')),
                ('leave_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.leaveapplication')),
            ],
            options={
                'ordering': ['leave_application__created', 'sequence', 'leave_application_approval_id'],
                'constraints': [models.UniqueConstraint(fields=('leave_application', 'approver_role'), name='unique_leave_application_approver_role')],
            },
        ),
    ]
