# Generated by Django 5.2.8 on 2026-03-23 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_recruitment_groups(apps, schema_editor):
    group_model = apps.get_model("auth", "Group")
    for name in ["IT Manager", "Division Chief"]:
        group_model.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_leavetyperule_filing_detail_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringRequest',
            fields=[
                ('hiring_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_no', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('requestor_role', models.CharField(choices=[('it_manager', 'IT Manager'), ('division_chief', 'Division Chief')], max_length=30)),
                ('headcount_requested', models.PositiveIntegerField(default=1)),
                ('employment_type', models.CharField(max_length=50)),
                ('hiring_reason', models.TextField()),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('justification', models.TextField()),
                ('current_approval_step', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_division_chief', 'Pending Division Chief Approval'), ('pending_hr', 'Pending HR Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_requests', to='core.division')),
                ('plantilla_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hiring_requests', to='core.cscplantilla')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_requests', to='core.position')),
                ('requestor_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_hiring_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-hiring_request_id'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('job_posting_id', models.AutoField(primary_key=True, serialize=False)),
                ('posting_no', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('requestor_role', models.CharField(choices=[('it_manager', 'IT Manager'), ('division_chief', 'Division Chief')], max_length=30)),
                ('job_title', models.CharField(max_length=150)),
                ('job_summary', models.TextField(blank=True)),
                ('job_description', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('employment_type', models.CharField(max_length=50)),
                ('work_location', models.CharField(blank=True, max_length=255)),
                ('open_slots', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_requestor_approval', 'Pending Requestor Approval'), ('pending_hr_publish_approval', 'Pending HR Publish Approval'), ('published', 'Published'), ('rejected', 'Rejected'), ('unpublished', 'Unpublished'), ('closed', 'Closed')], default='draft', max_length=40)),
                ('portal_status', models.CharField(choices=[('hidden', 'Hidden'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('expired', 'Expired'), ('closed', 'Closed')], default='hidden', max_length=20)),
                ('publish_start', models.DateTimeField(blank=True, null=True)),
                ('publish_end', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='core.division')),
                ('hiring_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_posting', to='core.hiringrequest')),
                ('plantilla_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='core.cscplantilla')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='core.position')),
                ('prepared_by_hr_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prepared_job_postings', to=settings.AUTH_USER_MODEL)),
                ('requestor_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_job_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-job_posting_id'],
            },
        ),
        migrations.CreateModel(
            name='HiringRequestApproval',
            fields=[
                ('hiring_request_approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('approver_role', models.CharField(choices=[('division_chief', 'Division Chief'), ('hr_approver', 'HR Approver')], max_length=30)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('decision_notes', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('approver_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiring_request_approvals', to=settings.AUTH_USER_MODEL)),
                ('hiring_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.hiringrequest')),
            ],
            options={
                'ordering': ['hiring_request__created', 'sequence', 'hiring_request_approval_id'],
                'constraints': [models.UniqueConstraint(fields=('hiring_request', 'approver_role'), name='unique_hiring_request_approval_role')],
            },
        ),
        migrations.CreateModel(
            name='JobPostingApproval',
            fields=[
                ('job_posting_approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('approver_role', models.CharField(choices=[('requestor', 'Requestor'), ('hr_publisher', 'HR Publisher')], max_length=30)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('decision_notes', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('approver_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_posting_approvals', to=settings.AUTH_USER_MODEL)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.jobposting')),
            ],
            options={
                'ordering': ['job_posting__created', 'sequence', 'job_posting_approval_id'],
                'constraints': [models.UniqueConstraint(fields=('job_posting', 'approver_role'), name='unique_job_posting_approval_role')],
            },
        ),
        migrations.RunPython(create_recruitment_groups, migrations.RunPython.noop),
    ]
