# Generated by Django 5.2.8 on 2025-12-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='division',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
