# Generated by Django 5.2.8 on 2026-01-13 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_modules', '0005_alter_employee_position'),
        ('hr_modules', '0002_remove_employee_division_delete_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_approver',
            fields=[
                ('emp_approver_id', models.AutoField(primary_key=True, serialize=False)),
                ('alt_division_chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_division_chief', to='employee_modules.employee')),
                ('alt_hr_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_hr_approver', to='employee_modules.employee')),
                ('alt_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_supervisor', to='employee_modules.employee')),
                ('division_chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_chief', to='employee_modules.employee')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver_employee', to='employee_modules.employee')),
                ('hr_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approver', to='employee_modules.employee')),
                ('immediate_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immediate_supervisor', to='employee_modules.employee')),
            ],
        ),
    ]
