# Generated by Django 5.2.8 on 2026-01-13 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_timerule'),
        ('employee_modules', '0005_alter_employee_position'),
        ('hr_modules', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('approver_id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_type', models.CharField(max_length=50)),
                ('alt_division_chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_division_chief', to='employee_modules.employee')),
                ('alt_hr_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_hr_approver', to='employee_modules.employee')),
                ('alt_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_supervisor', to='employee_modules.employee')),
                ('division_chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_chief', to='employee_modules.employee')),
                ('division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver_division', to='core.division')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver_employee', to='employee_modules.employee')),
                ('hr_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approver', to='employee_modules.employee')),
                ('immediate_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immediate_supervisor', to='employee_modules.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='emp_approver',
        ),
    ]
