# Generated by Django 5.2.8 on 2026-01-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_timerule'),
        ('employee_modules', '0005_alter_employee_position'),
        ('hr_modules', '0004_approver_delete_emp_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approver',
            name='division_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver_division', to='core.division'),
        ),
        migrations.AlterField(
            model_name='approver',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver_employee', to='employee_modules.employee'),
        ),
    ]
